spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gomaster-me/config-repo
server:
  port: 8888
management:
  security:
    enabled: false
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gomaster-me/config-repo
  rabbitmq:
    host: rabbitmq
