server:
  port: 7777
#  context-path: /event-service
management:
  security:
    enabled: false

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
#  data:
#    mongodb:
#      host: mongo

