server:
  port: 7777
#  context-path: /event-service
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
#  data:
#    mongodb:
#      host: mongo

